nome: GitHub Snake Game



sobre:

  # Agende o fluxo de trabalho para ser executado diariamente à meia-noite UTC

  agendar:

    - cron: "0 0 * * *"



  # Permitir o acionamento manual do fluxo de trabalho

  fluxo de trabalho_despacho:



  # Acionar o fluxo de trabalho em pushes para o branch principal

  empurrar:

    galhos:

      - principal



empregos:

  gerar:

    em execução: ubuntu-latest

    tempo limite-minutos: 10



    passos:

      # Etapa 1: Faça check-out do repositório

      - nome: Repositório de Checkout

        usos: ações/checkout@v3



      # Etapa 2: Gere as animações da cobra

      - nome: Gerar animações de cobras do GitHub Contributions

        usos: Platane/snk@v3

        com:

          # Nome de usuário do GitHub para gerar a animação para

          nome_de_usuário_github: ${{ github.repository_owner }}



          # Defina os arquivos de saída e suas configurações

          saídas: |

            dist/github-snake.svg

            dist/github-snake-dark.svg?palette=github-dark

            dist/ocean.gif?color_snake=laranja&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

        ambiente:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      # Etapa 3: Implante os arquivos gerados na ramificação 'output'

      - nome: Implantar no Branch de Saída

        usos: peaceiris/actions-gh-pages@v3

        com:

          github_token: ${{ secrets.GITHUB_TOKEN }}

          diretório_de_publicação: ./dist

          publish_branch: saída

          # Opcionalmente, você pode definir uma mensagem de confirmação personalizada

          commit_message: "Atualizar animação de cobra [pular ci]"

